#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

locale: en_US.UTF-8
timezone: Europe/Amsterdam

packages:
  - vim
  - podman
  - nftables

write_files:
  - path: /etc/sysconfig/nftables.conf
    owner: root:root
    permissions: "0644"
    content: |
      flush ruleset
      table inet nftables_svc {
        set allowed_protocols {
          type inet_proto
          elements = { icmp, icmpv6 }
        }
        set allowed_interfaces {
          type ifname
          elements = { "lo", "podman0", "veth0", "veth1" }
        }
        set allowed_tcp_dports {
          type inet_service
          elements = { 21, 22, 80, 443 }
        }
        chain allow {
          ct state established,related accept
          meta l4proto @allowed_protocols accept
          iifname @allowed_interfaces accept
          tcp dport @allowed_tcp_dports accept
        }
        chain INPUT {
          type filter hook input priority filter + 20
          policy accept
          jump allow
          reject with icmpx type port-unreachable
        }
      }
  - path: /etc/containers/networks/podman.json
    owner: root:root
    permissions: "0644"
    content: |
      {
        "name": "podman",
        "id": "2f259bab93aaaaa2542ba43ef33eb990d0999ee1b9924b557b7be53c0b7a1bb9",
        "driver": "bridge",
        "network_interface": "podman0",
        "created": "2024-03-13T19:40:29.895534643+01:00",
        "subnets": [
          {
            "subnet": "10.88.0.0/16",
            "gateway": "10.88.0.1"
          }
        ],
        "ipv6_enabled": false,
        "internal": false,
        "dns_enabled": true,
        "ipam_options": {
          "driver": "host-local"
        }
      }
  - path: /etc/nginx/nginx.conf
    owner: root:root
    permissions: "0644"
    content: |
      user nginx;
      worker_processes auto;
      error_log /var/log/nginx/error.log;
      pid /run/nginx.pid;

      include /usr/share/nginx/modules/*.conf;

      events {
          worker_connections 1024;
      }

      http {
          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';

          access_log  /var/log/nginx/access.log  main;

          resolver 10.88.0.1;  # !! DNS server for podman network

          sendfile            on;
          tcp_nopush          on;
          keepalive_timeout   65;
          types_hash_max_size 4096;

          include             /etc/nginx/mime.types;
          default_type        application/octet-stream;

          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              server_name _;
              return 404;
          }

          server {
            listen 80;
            listen [::]:80;
            server_name "stream.alma.orb.local";

            location / {
              set $upstream "http://dinxperfm.freeddns.org:8082";
              proxy_pass $upstream;
            }
          }

          server {
            listen 80;
            listen [::]:80;
            server_name "site.alma.orb.local";

            location / {
              set $upstream "http://systemd-dfmsite.dns.podman:3000";
              proxy_pass $upstream;
            }
          }
      }

  - path: /etc/containers/systemd/dfmsite.container
    owner: root:root
    permissions: "0755"
    content: |
      [Unit]
      Description=DinxperFM - Website

      [Install]
      WantedBy=multi-user.target

      [Container]
      Image=docker.io/dfmsite:latest
      AutoUpdate=local
      Exec=
      ReadOnly=true

  - path: /etc/containers/systemd/nginx.container
    owner: root:root
    permissions: "0755"
    content: |
      [Unit]
      Description=nginx

      [Install]
      WantedBy=multi-user.target

      [Container]
      Image=docker.io/nginx
      AutoUpdate=registry
      Exec=
      PublishPort=80:80
      PublishPort=443:443
      Volume=/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:z,ro

runcmd:
  - systemctl enable nftables && systemctl start nftables
  - systemctl enable nginx.service dfmsite.service
  - systemctl enable podman-auto-update.service podman-auto-update.timer
