version: "3"

services:
  traefik:
    restart: unless-stopped
    image: traefik:v3.0
    container_name: traefik-ingress
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --entrypoints.websecure.http.tls.certresolver=myresolver

      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=roel@jaroel.nl
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

  dfmsite:
    restart: unless-stopped
    image: dfmsite:latest
    container_name: dfmsite
    expose: [3000]
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dfmsite.rule=Host(`dfmsite.toffe.site`)
      - traefik.http.routers.dfmsite.entrypoints=websecure
      - traefik.http.routers.dfmsite.tls.certresolver=myresolver

networks:
  proxy:
    name: proxy
